#!/bin/sh
set -e

case "$1" in
remove | upgrade)
	# Clean up virtual environment
	rm -rf /opt/distiller-cm5-sdk/.venv
	rm -f /opt/distiller-cm5-sdk/uv.lock
	rm -f /opt/distiller-cm5-sdk/activate.sh
	rm -rf /opt/distiller-cm5-sdk/src
	
	# Update shared library cache
	ldconfig
	;;

purge)
	# Remove entire SDK directory
	rm -rf /opt/distiller-cm5-sdk
	
	# Update shared library cache
	ldconfig
	;;

failed-upgrade | abort-install | abort-upgrade | disappear)
	;;

*)
	echo "postrm called with unknown argument \`$1'" >&2
	exit 1
	;;
esac

#DEBHELPER#

exit 0